<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <LangVersion>latest</LangVersion>
    <Company>AutoVPN</Company>
    <Product>AutoVPN</Product>
    <Version>0.1.0</Version>
    <Copyright>Copyright © 2026 AutoVPN contributors</Copyright>
    <NeutralLanguage>ru</NeutralLanguage>
  </PropertyGroup>
</Project>
