<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>AutoVpn.Inventory</RootNamespace>
    <AssemblyName>autovpn-inventory</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AutoVpn.Infrastructure\AutoVpn.Infrastructure.csproj" />
    <ProjectReference Include="..\AutoVpn.Domain\AutoVpn.Domain.csproj" />
  </ItemGroup>
</Project>
