<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>AutoVpn.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AutoVpn.Domain\AutoVpn.Domain.csproj" />
    <ProjectReference Include="..\AutoVpn.Contracts\AutoVpn.Contracts.csproj" />
  </ItemGroup>
</Project>
